In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("C:/Users/GOWRI/Downloads/NYC.csv/NYC.csv")
df

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration
0,id2875421,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,-73.982155,40.767937,-73.964630,40.765602,N,455
1,id2377394,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,-73.980415,40.738564,-73.999481,40.731152,N,663
2,id3858529,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,-73.979027,40.763939,-74.005333,40.710087,N,2124
3,id3504673,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,-74.010040,40.719971,-74.012268,40.706718,N,429
4,id2181028,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,-73.973053,40.793209,-73.972923,40.782520,N,435
...,...,...,...,...,...,...,...,...,...,...,...
1458639,id2376096,2,2016-04-08 13:31:04,2016-04-08 13:44:02,4,-73.982201,40.745522,-73.994911,40.740170,N,778
1458640,id1049543,1,2016-01-10 07:35:15,2016-01-10 07:46:10,1,-74.000946,40.747379,-73.970184,40.796547,N,655
1458641,id2304944,2,2016-04-22 06:57:41,2016-04-22 07:10:25,1,-73.959129,40.768799,-74.004433,40.707371,N,764
1458642,id2714485,1,2016-01-05 15:56:26,2016-01-05 16:02:39,1,-73.982079,40.749062,-73.974632,40.757107,N,373
1458643,id1209952,1,2016-04-05 14:44:25,2016-04-05 14:47:43,1,-73.979538,40.781750,-73.972809,40.790585,N,198

In [4]:
df=pd.read_csv("C:/Users/GOWRI/Downloads/NYC.csv/NYC.csv")
df.head()

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration
0,id2875421,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,-73.982155,40.767937,-73.964630,40.765602,N,455
1,id2377394,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,-73.980415,40.738564,-73.999481,40.731152,N,663
2,id3858529,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,-73.979027,40.763939,-74.005333,40.710087,N,2124
3,id3504673,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,-74.010040,40.719971,-74.012268,40.706718,N,429
4,id2181028,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,-73.973053,40.793209,-73.972923,40.782520,N,435

In [5]:
df["trip_duration"]

0           455
1           663
2          2124
3           429
4           435
           ...
1458639     778
1458640     655
1458641     764
1458642     373
1458643     198
Name: trip_duration, Length: 1458644, dtype: int64

In [6]:
df.head()

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration
0,id2875421,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,-73.982155,40.767937,-73.964630,40.765602,N,455
1,id2377394,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,-73.980415,40.738564,-73.999481,40.731152,N,663
2,id3858529,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,-73.979027,40.763939,-74.005333,40.710087,N,2124
3,id3504673,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,-74.010040,40.719971,-74.012268,40.706718,N,429
4,id2181028,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,-73.973053,40.793209,-73.972923,40.782520,N,435

In [7]:
print(df.shape)

(1458644, 11)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1458644 entries, 0 to 1458643
Data columns (total 11 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   id                  1458644 non-null  str
 1   vendor_id           1458644 non-null  int64
 2   pickup_datetime     1458644 non-null  str
 3   dropoff_datetime    1458644 non-null  str
 4   passenger_count     1458644 non-null  int64
 5   pickup_longitude    1458644 non-null  float64
 6   pickup_latitude     1458644 non-null  float64
 7   dropoff_longitude   1458644 non-null  float64
 8   dropoff_latitude    1458644 non-null  float64
 9   store_and_fwd_flag  1458644 non-null  str
 10  trip_duration       1458644 non-null  int64
dtypes: float64(4), int64(3), str(4)
memory usage: 189.2 MB

In [9]:
df.shape

(1458644, 11)

In [10]:
df.describe

<bound method NDFrame.describe of                 id  vendor_id      pickup_datetime     dropoff_datetime  \
0        id2875421          2  2016-03-14 17:24:55  2016-03-14 17:32:30
1        id2377394          1  2016-06-12 00:43:35  2016-06-12 00:54:38
2        id3858529          2  2016-01-19 11:35:24  2016-01-19 12:10:48
3        id3504673          2  2016-04-06 19:32:31  2016-04-06 19:39:40
4        id2181028          2  2016-03-26 13:30:55  2016-03-26 13:38:10
...            ...        ...                  ...                  ...
1458639  id2376096          2  2016-04-08 13:31:04  2016-04-08 13:44:02
1458640  id1049543          1  2016-01-10 07:35:15  2016-01-10 07:46:10
1458641  id2304944          2  2016-04-22 06:57:41  2016-04-22 07:10:25
1458642  id2714485          1  2016-01-05 15:56:26  2016-01-05 16:02:39
1458643  id1209952          1  2016-04-05 14:44:25  2016-04-05 14:47:43

         passenger_count  pickup_longitude  pickup_latitude  \
0                      1        -73.982155        40.767937
1                      1        -73.980415        40.738564
2                      1        -73.979027        40.763939
3                      1        -74.010040        40.719971
4                      1        -73.973053        40.793209
...                  ...               ...              ...
1458639                4        -73.982201        40.745522
1458640                1        -74.000946        40.747379
1458641                1        -73.959129        40.768799
1458642                1        -73.982079        40.749062
1458643                1        -73.979538        40.781750

         dropoff_longitude  dropoff_latitude store_and_fwd_flag  trip_duration
0               -73.964630         40.765602                  N            455
1               -73.999481         40.731152                  N            663
2               -74.005333         40.710087                  N           2124
3               -74.012268         40.706718                  N            429
4               -73.972923         40.782520                  N            435
...                    ...               ...                ...            ...
1458639         -73.994911         40.740170                  N            778
1458640         -73.970184         40.796547                  N            655
1458641         -74.004433         40.707371                  N            764
1458642         -73.974632         40.757107                  N            373
1458643         -73.972809         40.790585                  N            198

[1458644 rows x 11 columns]>

In [11]:
df.isnull().sum()

id                    0
vendor_id             0
pickup_datetime       0
dropoff_datetime      0
passenger_count       0
pickup_longitude      0
pickup_latitude       0
dropoff_longitude     0
dropoff_latitude      0
store_and_fwd_flag    0
trip_duration         0
dtype: int64

In [12]:
df = df.dropna()

In [13]:
df["store_and_fwd_flag"].unique()

<ArrowStringArray>
['N', 'Y']
Length: 2, dtype: str

In [14]:
print(df.duplicated().sum())

0

In [15]:
df.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1458639    False
1458640    False
1458641    False
1458642    False
1458643    False
Length: 1458644, dtype: bool

In [16]:
df[df.duplicated()]

Empty DataFrame
Columns: [id, vendor_id, pickup_datetime, dropoff_datetime, passenger_count, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, store_and_fwd_flag, trip_duration]
Index: []

In [17]:
df = df.dropna()
df = df[df["passenger_count"] > 0]
df = df[df["trip_duration"] > 0]

In [18]:
df = df.dropna()

In [19]:
df = df[df["passenger_count"] > 0]

In [20]:
df["pickup_datetime"] = pd.to_datetime(df["pickup_datetime"])

df["pickup_hour"] = df["pickup_datetime"].dt.hour
df["pickup_day"] = df["pickup_datetime"].dt.dayofweek

In [21]:
df.describe()

,vendor_id,pickup_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,pickup_hour,pickup_day
count,1.458584e+06,1458584,1.458584e+06,1.458584e+06,1.458584e+06,1.458584e+06,1.458584e+06,1.458584e+06,1.458584e+06,1.458584e+06
mean,1.534952e+00,2016-04-01 10:11:23.485405,1.664598e+00,-7.397349e+01,4.075092e+01,-7.397342e+01,4.075180e+01,9.594611e+02,1.360657e+01,3.050354e+00
min,1.000000e+00,2016-01-01 00:00:17,1.000000e+00,-1.219333e+02,3.435970e+01,-1.219333e+02,3.218114e+01,1.000000e+00,0.000000e+00,0.000000e+00
25%,1.000000e+00,2016-02-17 16:47:08,1.000000e+00,-7.399187e+01,4.073735e+01,-7.399133e+01,4.073589e+01,3.970000e+02,9.000000e+00,1.000000e+00
50%,2.000000e+00,2016-04-01 17:20:18,1.000000e+00,-7.398174e+01,4.075410e+01,-7.397975e+01,4.075452e+01,6.620000e+02,1.400000e+01,3.000000e+00
75%,2.000000e+00,2016-05-15 03:57:12.250000,2.000000e+00,-7.396733e+01,4.076836e+01,-7.396302e+01,4.076981e+01,1.075000e+03,1.900000e+01,5.000000e+00
max,2.000000e+00,2016-06-30 23:59:39,9.000000e+00,-6.133553e+01,5.188108e+01,-6.133553e+01,4.392103e+01,3.526282e+06,2.300000e+01,6.000000e+00
std,4.987770e-01,NaN,1.314226e+00,7.090225e-02,3.288019e-02,7.064353e-02,3.588951e-02,5.237064e+03,6.399588e+00,1.954031e+00

In [22]:
df.head()

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_hour,pickup_day
0,id2875421,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,-73.982155,40.767937,-73.964630,40.765602,N,455,17,0
1,id2377394,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,-73.980415,40.738564,-73.999481,40.731152,N,663,0,6
2,id3858529,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,-73.979027,40.763939,-74.005333,40.710087,N,2124,11,1
3,id3504673,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,-74.010040,40.719971,-74.012268,40.706718,N,429,19,2
4,id2181028,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,-73.973053,40.793209,-73.972923,40.782520,N,435,13,5

In [25]:
# Create weekend/weekday column
df['pickup_daytype'] = df['pickup_day'].apply(lambda x: 'Weekend' if x >= 5 else 'Weekday')

In [26]:
df.head()

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,pickup_hour,pickup_day,pickup_daytype
0,id2875421,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,-73.982155,40.767937,-73.964630,40.765602,N,455,17,0,Weekday
1,id2377394,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,-73.980415,40.738564,-73.999481,40.731152,N,663,0,6,Weekend
2,id3858529,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,-73.979027,40.763939,-74.005333,40.710087,N,2124,11,1,Weekday
3,id3504673,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,-74.010040,40.719971,-74.012268,40.706718,N,429,19,2,Weekday
4,id2181028,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,-73.973053,40.793209,-73.972923,40.782520,N,435,13,5,Weekend

In [27]:
df = df.drop('store_and_fwd_flag', axis=1)

In [28]:
print(df.columns)

Index(['id', 'vendor_id', 'pickup_datetime', 'dropoff_datetime',
       'passenger_count', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'trip_duration', 'pickup_hour',
       'pickup_day', 'pickup_daytype'],
      dtype='str')

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 1458584 entries, 0 to 1458643
Data columns (total 13 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id                 1458584 non-null  str
 1   vendor_id          1458584 non-null  int64
 2   pickup_datetime    1458584 non-null  datetime64[us]
 3   dropoff_datetime   1458584 non-null  str
 4   passenger_count    1458584 non-null  int64
 5   pickup_longitude   1458584 non-null  float64
 6   pickup_latitude    1458584 non-null  float64
 7   dropoff_longitude  1458584 non-null  float64
 8   dropoff_latitude   1458584 non-null  float64
 9   trip_duration      1458584 non-null  int64
 10  pickup_hour        1458584 non-null  int32
 11  pickup_day         1458584 non-null  int32
 12  pickup_daytype     1458584 non-null  str
dtypes: datetime64[us](1), float64(4), int32(2), int64(3), str(3)
memory usage: 193.7 MB

In [30]:
df

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,pickup_hour,pickup_day,pickup_daytype
0,id2875421,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,-73.982155,40.767937,-73.964630,40.765602,455,17,0,Weekday
1,id2377394,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,-73.980415,40.738564,-73.999481,40.731152,663,0,6,Weekend
2,id3858529,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,-73.979027,40.763939,-74.005333,40.710087,2124,11,1,Weekday
3,id3504673,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,-74.010040,40.719971,-74.012268,40.706718,429,19,2,Weekday
4,id2181028,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,-73.973053,40.793209,-73.972923,40.782520,435,13,5,Weekend
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458639,id2376096,2,2016-04-08 13:31:04,2016-04-08 13:44:02,4,-73.982201,40.745522,-73.994911,40.740170,778,13,4,Weekday
1458640,id1049543,1,2016-01-10 07:35:15,2016-01-10 07:46:10,1,-74.000946,40.747379,-73.970184,40.796547,655,7,6,Weekend
1458641,id2304944,2,2016-04-22 06:57:41,2016-04-22 07:10:25,1,-73.959129,40.768799,-74.004433,40.707371,764,6,4,Weekday
1458642,id2714485,1,2016-01-05 15:56:26,2016-01-05 16:02:39,1,-73.982079,40.749062,-73.974632,40.757107,373,15,1,Weekday
1458643,id1209952,1,2016-04-05 14:44:25,2016-04-05 14:47:43,1,-73.979538,40.781750,-73.972809,40.790585,198,14,1,Weekday